travis:
  secure:
    BINSTAR_TOKEN: v/wlfCbLW6oKngK67gu4mFAaMvf47sWXAopta/rSuVRNN/yCu9y3uS/8sEbPjcsewFjX8fE8TeVVmE9hAgzLb3p015baA3jxSbiBuLBo0cn3w2hzbrJ+HAEwsa4j0UU3RIC7HrzyIC9UPdEbHJQRx/9YbWDUbhXCN//Y9wC11tU9wD2qDfkFMty23YXYTcXMoHyaP+oVKaNw1/lfhGp2LcUOXVKISAXg9k8c5Zyxcr4nKF7z5H6FJqb0hG2U834z0/AZajiSOAZYN2jJ5d0Zw+gvjY3gUcgcjHX0H3DiJ6ptA4j1HWdE2sApsBvfJ9y57iwxsJnMK2z5+t1rlPSo4dxVGtQdDnwpYks0c+RJhq38ZjLitxJO8+UBPVo+FZPsMwTijROLbet49GdgqykLEkKtMPSGJhcI59v3yvD5NJl9F95ipwwJ2TAq8RT+HoPhIV+DtjDXo/75d7RGzI4P2gHzl3JkPtb0kAVlzK//A1e6pJSHkFnjG4PBNu4l9ijwG9sXDzzNwbVQw/0lJTxOBls50luQh+aXk4SCgAU7nwugTe4rdI3enah0GIf7num1fP7av5nZ4JknjHxUqVBZK9+fL6ntwJ9SGdrse2U3gvdBcU4SNAvfiT9qjQCKX+j+MOUd+UwimL25/v34QcabChFTi5D+/ovlNafoWi8wiDg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
